[workspace]

members = [
    "chapter_1/hello_cargo",
    "chapter_2/guessing_game",
    "chapter_3/branches",
    "chapter_3/functions",
    "chapter_3/repetition",
    "chapter_3/variables"]
resolver = "3"

